- pkg:maven/de.alphaomega-it.bbconfigmapper/BBConfigMapper@1.0?classifier=sources
- pkg:maven/de.alphaomega-it.bbconfigmapper/BBConfigMapper@1.1?classifier=sources
- pkg:maven/de.alphaomega-it.bbconfigmapper/BBConfigMapper@1.2?classifier=sources
- pkg:maven/de.alphaomega-it.bbconfigmapper/BBConfigMapper@1.5?classifier=sources
