- pkg:maven/io.github.thechance101/chart@1.0?classifier=sources
- pkg:maven/io.github.thechance101/chart@1.1.0?classifier=sources
- pkg:maven/io.github.thechance101/chart@1.1?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-0.0.1?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-0.0.2?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-0.0.3?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-0.0.4?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-0.0.5?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-1.0.0?classifier=sources
- pkg:maven/io.github.thechance101/chart@Beta-1.0.1?classifier=sources
