- pkg:maven/com.solace.connector.core.resource/pubsubplus-connector-docker-compose-resource-bundle@1.1.1
- pkg:maven/com.solace.connector.core.resource/pubsubplus-connector-docker-compose-resource-bundle@1.1.1?classifier=sources
