- pkg:maven/org.kie/kie-addons-quarkus-monitoring-prometheus-deployment@10.0.0
- pkg:maven/org.kie/kie-addons-quarkus-monitoring-prometheus-deployment@10.0.0?classifier=sources
- pkg:maven/org.kie/kie-addons-quarkus-monitoring-prometheus-deployment@10.1.0
- pkg:maven/org.kie/kie-addons-quarkus-monitoring-prometheus-deployment@10.1.0?classifier=sources
