- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.2
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.2?classifier=sources
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.3
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.3?classifier=sources
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.4
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.4?classifier=sources
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.6
- pkg:maven/com.netifi/netifi-metrics-prometheus@1.6.6?classifier=sources
