- pkg:maven/org.apache.jclouds.labs/docker@1.8.0
- pkg:maven/org.apache.jclouds.labs/docker@1.8.0?classifier=sources
- pkg:maven/org.apache.jclouds.labs/docker@1.8.1
- pkg:maven/org.apache.jclouds.labs/docker@1.8.1?classifier=sources
- pkg:maven/org.apache.jclouds.labs/docker@1.9.0
- pkg:maven/org.apache.jclouds.labs/docker@1.9.0?classifier=sources
- pkg:maven/org.apache.jclouds.labs/docker@1.9.1
- pkg:maven/org.apache.jclouds.labs/docker@1.9.1?classifier=sources
