- pkg:maven/de.weltraumschaf.commons/config@1.1.0
- pkg:maven/de.weltraumschaf.commons/config@1.1.0?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@1.1.1
- pkg:maven/de.weltraumschaf.commons/config@1.1.1?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@1.1.2
- pkg:maven/de.weltraumschaf.commons/config@1.1.2?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@1.1.3
- pkg:maven/de.weltraumschaf.commons/config@1.1.3?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@2.0.0
- pkg:maven/de.weltraumschaf.commons/config@2.0.0?classifier=sources
- pkg:maven/de.weltraumschaf.commons/config@2.1.0
- pkg:maven/de.weltraumschaf.commons/config@2.1.0?classifier=sources
