- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-caffeine@0.0.1-releasetest1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-caffeine@1.3.2?classifier=sources
