- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.10.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.11.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.12.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.13.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.14.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.15.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.15.1?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.16.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.16.1?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.17.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.18.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.19.0?classifier=sources
- pkg:maven/ch.admin.bit.jeap/jeap-archrepo-importer-prometheus@1.20.0?classifier=sources
