- pkg:maven/org.http4s/http4s-prometheus-client-metrics_2.12@0.19.0-M2
- pkg:maven/org.http4s/http4s-prometheus-client-metrics_2.12@0.19.0-M2?classifier=sources
- pkg:maven/org.http4s/http4s-prometheus-client-metrics_2.12@0.19.0-M3
- pkg:maven/org.http4s/http4s-prometheus-client-metrics_2.12@0.19.0-M3?classifier=sources
