- pkg:maven/ai.apptuit.metrics/metrics-apptuit-prometheus-client@0.9.6
- pkg:maven/ai.apptuit.metrics/metrics-apptuit-prometheus-client@0.9.6?classifier=sources
- pkg:maven/ai.apptuit.metrics/metrics-apptuit-prometheus-client@0.9.7
- pkg:maven/ai.apptuit.metrics/metrics-apptuit-prometheus-client@0.9.7?classifier=sources
