- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.2.0
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.2.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.2.1
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.2.1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.3.0
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.3.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.3.1
- pkg:maven/io.prometheus/prometheus-metrics-instrumentation-dropwizard5@1.3.1?classifier=sources
