- pkg:maven/com.threatconnect.app/playbooks-core@2.7.0
- pkg:maven/com.threatconnect.app/playbooks-core@2.7.0?classifier=sources
- pkg:maven/com.threatconnect.app/playbooks-core@2.7.3
- pkg:maven/com.threatconnect.app/playbooks-core@2.7.3?classifier=sources
- pkg:maven/com.threatconnect.app/playbooks-core@2.7.5
- pkg:maven/com.threatconnect.app/playbooks-core@2.7.5?classifier=sources
