- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.10?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.4?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.5?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.6?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.7?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.8?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.9?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.4.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.4.1?classifier=sources
