- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.4?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-otel-agent-resources@1.3.5?classifier=sources
